/// @file
/// @brief Character sequences for special keys on an ANSI terminal
///
/// This allows keyboard key presses to be translated into something ANSI terminals understand.

//#define ENABLE_TRACING

#include "vga_terminal.h"
#include "azalea/keyboard.h"

/// @brief Map of KEYS values to terminal keystrokes
///
/// This map translates values read from a keyboard into those that would be generated by an ANSI terminal. Note that
/// the vga terminal object already handles printable characters directly and only references this table for non-
/// printable characters, but they are included to aid programmers reading the table in future.
terms::vga_term_keymap_entry terms::vga_keymap[static_cast<int>(KEYS::MAX_KNOWN) + 1]
{
  { 0, nullptr }, // 0 - UNK
  { 0, nullptr }, // 1 - Nothing assigned
  { 0, nullptr }, // 2 - Nothing assigned
  { 0, nullptr }, // 3 - Nothing assigned
  { 0, nullptr }, // 4 - Nothing assigned
  { 0, nullptr }, // 5 - Nothing assigned
  { 0, nullptr }, // 6 - Nothing assigned
  { 0, nullptr }, // 7 - Nothing assigned
  { 1, "\b" }, // 8 - backspace
  { 1, "\t" }, // 9 - tab
  { 1, "\r" }, // 10 - enter
  { 1, "\r" }, // 11 - return
  { 0, nullptr }, // 12 - Nothing assigned
  { 0, nullptr }, // 13 - Nothing assigned
  { 0, nullptr }, // 14 - Nothing assigned
  { 0, nullptr }, // 15 - Nothing assigned
  { 0, nullptr }, // 16 - Nothing assigned
  { 0, nullptr }, // 17 - Nothing assigned
  { 0, nullptr }, // 18 - Nothing assigned
  { 0, nullptr }, // 19 - Nothing assigned
  { 0, nullptr }, // 20 - Nothing assigned
  { 0, nullptr }, // 21 - Nothing assigned
  { 0, nullptr }, // 22 - Nothing assigned
  { 0, nullptr }, // 23 - Nothing assigned
  { 0, nullptr }, // 24 - Nothing assigned
  { 0, nullptr }, // 25 - Nothing assigned
  { 0, nullptr }, // 26 - Nothing assigned
  { 1, "\x1b" }, // 27 - Escape
  { 0, nullptr }, // 28 - Nothing assigned
  { 0, nullptr }, // 29 - Nothing assigned
  { 0, nullptr }, // 30 - Nothing assigned
  { 0, nullptr }, // 31 - Nothing assigned
  { 1, " " }, // 32 - Space
  { 0, nullptr }, // 33 - Nothing assigned
  { 0, nullptr }, // 34 - Nothing assigned
  { 0, nullptr }, // 35 - Nothing assigned
  { 0, nullptr }, // 36 - Nothing assigned
  { 0, nullptr }, // 37 - Nothing assigned
  { 0, nullptr }, // 38 - Nothing assigned
  { 1, "'" }, // 39 - Single quote
  { 0, nullptr }, // 40 - Nothing assigned
  { 0, nullptr }, // 41 - Nothing assigned
  { 0, nullptr }, // 42 - Nothing assigned
  { 0, nullptr }, // 43 - Nothing assigned
  { 1, "," }, // 44 - Comma
  { 1, "-" }, // 45 - Dash
  { 1, "." }, // 46 - Main keyboard period
  { 1, "/" }, // 47 - Slash
  { 1, "0" }, // 48 - Nothing assigned
  { 1, "1" }, // 49 - Nothing assigned
  { 1, "2" }, // 50 - Nothing assigned
  { 1, "3" }, // 51 - Nothing assigned
  { 1, "4" }, // 52 - Nothing assigned
  { 1, "5" }, // 53 - Nothing assigned
  { 1, "6" }, // 54 - Nothing assigned
  { 1, "7" }, // 55 - Nothing assigned
  { 1, "8" }, // 56 - Nothing assigned
  { 1, "9" }, // 57 - Nothing assigned
  { 1, nullptr }, // 58 - Nothing assigned
  { 1, ";" }, // 59 - Semi-colon
  { 0, nullptr }, // 60 - Nothing assigned
  { 0, "=" }, // 61 - Equals
  { 0, nullptr }, // 62 - Nothing assigned
  { 0, nullptr }, // 63 - Nothing assigned
  { 0, nullptr }, // 64 - Nothing assigned
  { 1, "A" }, // 65 - A
  { 1, "B" }, // 66 - B
  { 1, "C" }, // 67 - C
  { 1, "D" }, // 68 - D
  { 1, "E" }, // 69 - E
  { 1, "F" }, // 70 - F
  { 1, "G" }, // 71 - G
  { 1, "H" }, // 72 - H
  { 1, "I" }, // 73 - I
  { 1, "J" }, // 74 - J
  { 1, "K" }, // 75 - K
  { 1, "L" }, // 76 - L
  { 1, "M" }, // 77 - M
  { 1, "N" }, // 78 - N
  { 1, "O" }, // 79 - O
  { 1, "P" }, // 80 - P
  { 1, "Q" }, // 81 - Q
  { 1, "R" }, // 82 - R
  { 1, "S" }, // 83 - S
  { 1, "T" }, // 84 - T
  { 1, "U" }, // 85 - U
  { 1, "V" }, // 86 - V
  { 1, "W" }, // 87 - W
  { 1, "X" }, // 88 - X
  { 1, "Y" }, // 89 - Y
  { 1, "Z" }, // 90 - Z
  { 1, "[" }, // 91 - [
  { 1, "\\" }, // 92 - Backslash
  { 1, "]" }, // 93 - ]
  { 0, nullptr }, // 94 - Nothing assigned
  { 1, "#" }, // 95 - Hash/tilde key
  { 1, "`" }, // 96 - Back tick
  { 0, nullptr }, // 97 - Nothing assigned
  { 0, nullptr }, // 98 - Nothing assigned
  { 0, nullptr }, // 99 - Nothing assigned
  { 1, "0" }, // 100 - Keypad 0
  { 1, "1" }, // 101 - Keypad 1
  { 1, "2" }, // 102 - Keypad 2
  { 1, "3" }, // 103 - Keypad 3
  { 1, "4" }, // 104 - Keypad 4
  { 1, "5" }, // 105 - Keypad 5
  { 1, "6" }, // 106 - Keypad 6
  { 1, "7" }, // 107 - Keypad 7
  { 1, "8" }, // 108 - Keypad 8
  { 1, "9" }, // 109 - Keypad 9
  { 1, "+" }, // 110 - Keypad +
  { 1, "-" }, // 111 - Keypad -
  { 1, "*" }, // 112 - Keypad *
  { 1, "/" }, // 113 - Keypad /
  { 1, "." }, // 114 - Keypad .
  { 1, "\n" }, // 115 - Keypad enter
  { 1, "=" }, // 116 - Keypad =
  { 1, "," }, // 117 - Keypad ,
  { 0, nullptr }, // 118 - Nothing assigned
  { 0, nullptr }, // 119 - Nothing assigned
  { 0, nullptr }, // 120 - Nothing assigned
  { 3, "\x1b[M" }, // 121 - F1
  { 3, "\x1b[N" }, // 122 - F2
  { 3, "\x1b[O" }, // 123 - F3
  { 3, "\x1b[P" }, // 124 - F4
  { 3, "\x1b[Q" }, // 125 - F5
  { 3, "\x1b[R" }, // 126 - F6
  { 3, "\x1b[S" }, // 127 - F7
  { 3, "\x1b[T" }, // 128 - F8
  { 3, "\x1b[U" }, // 129 - F9
  { 3, "\x1b[V" }, // 130 - F10
  { 3, "\x1b[W" }, // 131 - F11
  { 3, "\x1b[X" }, // 132 - F12
  { 3, "\x1b[Y" }, // 133 - F13
  { 0, nullptr }, // 134 - F14
  { 3, "\x1b[a" }, // 135 - F15
  { 3, "\x1b[b" }, // 136 - F16
  { 3, "\x1b[c" }, // 137 - F17
  { 3, "\x1b[d" }, // 138 - F18
  { 3, "\x1b[e" }, // 139 - F19
  { 3, "\x1b[f" }, // 140 - F20
  { 0, nullptr }, // 141 - Left Alt
  { 0, nullptr }, // 142 - Right Alt
  { 0, nullptr }, // 143 - Left Control
  { 0, nullptr }, // 144 - Right Control
  { 0, nullptr }, // 145 - Left shift
  { 0, nullptr }, // 146 - Right shift
  { 0, nullptr }, // 147 - Nothing assigned
  { 0, nullptr }, // 148 - Nothing assigned
  { 0, nullptr }, // 149 - Nothing assigned
  { 0, nullptr }, // 150 - Num lock
  { 0, nullptr }, // 151 - Caps lock
  { 0, nullptr }, // 152 - Scroll lock
  { 4, "\x1b[1~" }, // 153 - Home
  { 4, "\x1b[2~" }, // 154 - Insert
  { 4, "\x1b[3~" }, // 155 - Delete
  { 4, "\x1b[4~" }, // 156 - End
  { 0, nullptr }, // 157 - Nothing assigned
  { 0, nullptr }, // 158 - Nothing assigned
  { 0, nullptr }, // 159 - Nothing assigned
  { 3, "\x1b[A" }, // 160 - Up
  { 3, "\x1b[B" }, // 161 - Down
  { 3, "\x1b[D" }, // 162 - Left
  { 3, "\x1b[C" }, // 163 - Right
  { 4, "\x1b[6~" }, // 164 - Page Down
  { 4, "\x1b[5~" }, // 165 - Page Up
  { 0, nullptr }, // 166 - F21
  { 0, nullptr }, // 167 - F22
  { 0, nullptr }, // 168 - F23
  { 0, nullptr }, // 169 - F24
  { 0, nullptr }, // 170 - Left Windows Key
  { 0, nullptr }, // 171 - Right Windows Key
  { 0, nullptr }, // 172 - Nothing assigned
  { 0, nullptr }, // 173 - Nothing assigned
  { 0, nullptr }, // 174 - Nothing assigned
  { 0, nullptr }, // 175 - Nothing assigned
  { 0, nullptr }, // 176 - Nothing assigned
  { 0, nullptr }, // 177 - Nothing assigned
  { 0, nullptr }, // 178 - Nothing assigned
  { 0, nullptr }, // 179 - Nothing assigned
  { 0, nullptr }, // 180 - Multimedia - Play
  { 0, nullptr }, // 181 - Multimedia - Previous track
  { 0, nullptr }, // 182 - Multimedia - Next track
  { 0, nullptr }, // 183 - Multimedia - Media select
  { 0, nullptr }, // 184 - Multimedia - Volume down
  { 0, nullptr }, // 185 - Multimedia - Volume up
  { 0, nullptr }, // 186 - Multimedia - Mute
  { 0, nullptr }, // 187 - Multimedia - Calculator
  { 0, nullptr }, // 188 - Multimedia - Apps
  { 0, nullptr }, // 189 - Nothing assigned
  { 0, nullptr }, // 190 - Multimedia - WWW Home
  { 0, nullptr }, // 191 - Multimedia - WWW Search
  { 0, nullptr }, // 192 - Multimedia - WWW Back
  { 0, nullptr }, // 193 - Multimedia - WWW Forward
  { 0, nullptr }, // 194 - Multimedia - WWW Stop
  { 0, nullptr }, // 195 - Multimedia - WWW Refresh
  { 0, nullptr }, // 196 - Multimedia - WWW Favourites
  { 0, nullptr }, // 197 - Multimedia - WWW My PC
  { 0, nullptr }, // 198 - Multimedia - WWW Email
  { 0, nullptr }, // 199 - Nothing assigned
  { 0, nullptr }, // 200 - ACPI Power
  { 0, nullptr }, // 201 - ACPI Sleep
  { 0, nullptr }, // 202 - ACPI Wake
};
