# Kernel Memory library.

files = ["misc.cpp",
         "physical.cpp",
         "virtual.cpp",
         "x64/mem-x64.cpp",
         "x64/mem_pml4-x64.cpp",
         "x64/mem_support-x64.asm",
         "x64/mem_pat-x64.cpp",
        ]

Import('env')
obj = env.Library("mem", files)
Return ("obj") 