# Kernel Object Manager library.

files = [
         "handled_obj.cpp",
         "handles.cpp",
         "object_mgr.cpp",
        ]

Import('env')
obj = env.Library("object_mgr", files)
Return ("obj")