# ACPI library. Incorporates necessary parts of ACPICA

Import('env')
obj = env.Library("acpi", [ "acpi.cpp",
                            "acpi_interrupt.asm",
                            "acpi_osl.cpp",
                            "acpi_output.cpp",
                          ])
Return ("obj") 