# Klib Miscellany library.

Import('env')
obj = env.Library("klib-misc", [
                                "math_hacks.cpp",
                                "cpp_support.cpp",
                               ])
Return ("obj")