# Klib C-environment helpers library.

Import('env')
obj = env.Library("klib-c-helpers", [
                                      "allocator_templates.cpp",
                                      "buffers.cpp",
                                      "string_fns.cpp",
                                      "strerror.cpp",
                                    ])
Return ("obj")