# ACPI library. Incorporates necessary parts of ACPICA

Import('env')
obj = env.Library("acpi", [ "acpi.cpp",
                            "acpi_devices.cpp",
                            "acpi_osl.cpp",
                          ])
Return ("obj")