# Azalea test suite for tests that can only run on a live kernel.

Import('env')

obj = [ ]

files = [
  "online_test.cpp",

  "fake_functions.cpp",

  "futex/futex_1.cpp",

  "pthread/pthread_create.cpp",
  "pthread/pthread_mutex.cpp",
]

for f in files:
  obj = obj + [ env.Object(f) ]

Return ("obj")
