# Klib Memory library.

Import('env')
obj = env.Library("klib-memory",
                  [
                    "memory.cpp",
                    "mem_operators.cpp",
                    "mem_helpers.cpp",
                  ])
Return ("obj")