# Kernel System Tree library.

Import('env')
files = [ "system_tree.cpp",
          "system_tree_simple_branch.cpp",
          "system_tree_root.cpp", 
        ]
obj = env.Library("system_tree", files)
Return ("obj") 