# Object Manager test program.

Import('env')
obj = env.Library("object-mgr-test", [ "object_mgr_1.cpp", 
                                       "object_mgr_test_list.cpp",
                                     ])
Return ("obj") 