# Klib C-environment helpers library.

Import('env')
obj = env.Library("klib-c-helpers", [ "buffers.cpp",
                                      "printf_fns.cpp",
                                      "string_fns.cpp",
                                    ])
Return ("obj") 